CREATE TABLE member(
id SERIAL PRIMARY KEY,
username VARCHAR(15) NOT NULL UNIQUE, 
password VARCHAR(255) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE trip(
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL, 
destination VARCHAR(255) NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL,
member_id INT NOT NULL, 
FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE activity(
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL, 
location VARCHAR(255) NOT NULL,
trip_id INT NOT NULL, 
FOREIGN KEY (trip_id) REFERENCES trip(id)
);